name = "TDD"
uuid = "ff7f212f-1b9a-4100-adcb-f02264867e90"
authors = ["Lizzie <e.tilden@wustl.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
